service: groot-serverless

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  download:
    handler: functions/download.handler
    events:
      - http:
          path: /api
          method: post


custom:
  serverless-offline:
    httpPort: 5000