name: API

on:
  push:
    branches:
      - main
    paths:
      - .lambda/**
      - lambda_deployment.yml

jobs:
  test:
    name: 'Test lambda'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test

  deploy:
    needs: test
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Deploy Labmda
        run: yarn api:deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
